apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
replicas:
  - name: devsecops-demo
    count: 1
images:
  - name: ghcr.io/OWNER/REPO/devsecops-demo
    newTag: REPLACE_ME
